---
title: "STAT 886 Project R"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
library(R2OpenBUGS)
library(rstan)
library(brms)
library(StanHeaders)
```

```{r summary, echo=TRUE}
cars <- read.csv("auto-mpg-clean.csv")
cars_no_char <- read.csv("auto-mpg-clean-no-car.csv")
summary(cars)
```

## Graphs MPG vs Explanatory variables
```{r, plots}
ggplot(data = cars, aes(x=mpg)) + geom_histogram()

ggplot(data = cars, aes(x=acceleration, y=mpg)) + geom_point(colour="cyan3") + geom_smooth(methed = lm(data=cars, formula=log(mpg)~acceleration)) + ggtitle("MPG vs. Acceleration")

ggplot(data = cars, aes(x=model.year, y=mpg)) + geom_point(colour="red1") + geom_smooth(methed = lm(data=cars, formula=log(mpg)~model.year)) + ggtitle("MPG vs. Model Year")

ggplot(data = cars, aes(x=weight, y=mpg)) + geom_point(colour="orange2") + geom_smooth(methed = lm(data=cars, formula=log(mpg)~weight)) + ggtitle("MPG vs. Weight")

ggplot(data = cars, aes(x=cylinders, y=mpg)) + geom_point(colour="olivedrab") + geom_smooth(methed = lm(data=cars, formula=log(mpg)~cylinders)) + ggtitle("MPG vs. Number of Cylinders")

ggplot(data = cars, aes(x=displacement, y=mpg)) + geom_point(colour="purple1") + geom_smooth(methed = lm(data=cars, formula=log(mpg)~weight)) + ggtitle("MPG vs. Engine Displacement")

ggplot(data = cars, aes(x=horsepower, y=mpg)) + geom_point(colour="yellow3") + geom_smooth(methed = lm(data=cars, formula=log(mpg)~horsepower)) + ggtitle("MPG vs. Horsepower")
```


## Frequentist models

```{r, ols models, echo=TRUE}
model_all_linear <- lm(data=cars, mpg ~ cylinders + displacement + horsepower + weight + acceleration + origin + model.year)
summary(model_all_linear)

model_all_log_linear <- lm(data=cars, log(mpg) ~ cylinders + displacement + horsepower + weight + acceleration + origin + model.year)
summary(model_all_log_linear)

model_log_no_corr <- lm(data = cars, log(mpg)~weight + acceleration + model.year)

summary(model_log_no_corr)
```


## WinBUGS

### All terms
```{r, echo=TRUE}
N <- 392


model <- function() {
for(i in 1:N){
mpg[i] ~ dnorm(mu[i], tau)
mu[i] <- alpha + beta1*cylinders[i] + beta2*weight[i] + beta3*displacement[i] + beta4*model.year[i] + beta5*horsepower[i] + beta6*origin[i] + beta7*acceleration[i]
}
# priors
alpha ~ dnorm(0, .001)
beta1 ~ dunif(-1000,1000)
beta2 ~ dunif(-1000,1000)
beta3 ~ dunif(-1000,1000)
beta4 ~ dunif(-1000,1000)
beta5 ~ dunif(-1000, 1000)
beta6 ~ dunif(-1000, 1000)
beta7 ~ dunif(-1000, 1000)
tau ~ dgamma(0.5,0.5)
}

logmpg <- log(cars$mpg)

data <- list(mpg=logmpg, cylinders=cars$cylinders, weight=cars$weight, model.year=cars$model.year, origin = cars$origin, horsepower=cars$horsepower, acceleration = cars$acceleration, displacement=cars$displacement, N=N)

inits <- function(){
list(alpha=rnorm(1), beta1=rnorm(1), beta2=rnorm(1), beta3 = rnorm(1), beta4 = rnorm(1), beta5 = rnorm(1), beta6 = rnorm(1), beta7 = rnorm(1), tau=runif(1,0,2))
}

parameters <- c("alpha", "beta1", "beta2", "beta3", "beta4", "beta5", "beta6", "beta7", "tau")


sims <- bugs(data=data, inits=inits, parameters.to.save = c("alpha", "beta1", "beta2", "beta3", "beta4", "beta5", "beta6", "beta7", "tau"), model.file = model, n.chains=1, n.iter=10000)

plot(sims, display.parallel = TRUE)

b1 <- sims$sims.array[,,"beta1"]

plot(b1, type='l', col="red")

plot(density(b1),lwd=2,col="red")

b2 <- sims$sims.array[,,"beta2"]

plot(b2, type='l', col="red")

plot(density(b2),lwd=2,col="red")

b3 <- sims$sims.array[,,"beta3"]

plot(b3, type='l', col="red")

plot(density(b3),lwd=2,col="red")

b4 <- sims$sims.array[,,"beta4"]

plot(b4, type='l', col="red")

plot(density(b1),lwd=2,col="red")

b5 <- sims$sims.array[,,"beta5"]

plot(b5, type='l', col="red")

plot(density(b5),lwd=2,col="red")

b6 <- sims$sims.array[,,"beta6"]

plot(b6, type='l', col="red")

plot(density(b6),lwd=2,col="red")

b7 <- sims$sims.array[,,"beta7"]

plot(b7, type='l', col="red")

plot(density(b7),lwd=2,col="red")
```

## Weight
```{r, echo=TRUE}
N <- 392

model <- function() {
for(i in 1:N){
mpg[i] ~ dnorm(mu[i], tau)
mu[i] <- alpha + beta1*model.year[i] +beta2*acceleration[i]+ beta3*weight[i]  
}
# priors
alpha ~ dnorm(0, .001)
beta1 ~ dunif(-1000,1000)
beta2 ~ dunif(-1000, 1000)
beta3 ~ dunif(-1000, 1000)
tau ~ dgamma(0.5,0.5)
}

logmpg <- log(cars$mpg)

data <- list(mpg=logmpg, model.year=cars$model.year, weight = cars$weight, acceleration=cars$acceleration, N=N)

inits <- function(){
list(alpha=rnorm(1), beta1 = rnorm(1), beta2 = rnorm(1), beta3 = rnorm(1), tau=runif(1,0,2))
}

parameters <- c("alpha", "beta1", "beta2", "beta3","tau")


sims <- bugs(data=data, inits=inits, parameters.to.save = c("alpha", "beta1", "beta2", "beta3", "tau"), model.file = model, n.chains=1, n.iter=100000, n.burnin=10000, digits=5)

print(sims, digits.summary = 5)

alpha<- sims$sims.array[,,"alpha"]

plot(alpha, type='l', col="red")

plot(density(alpha), lwd=2, col="red")

tau <- sims$sims.array[,,"tau"]

plot(tau, type='l', col="red")

plot(density(tau), lwd=2, col="red")

beta1 <- sims$sims.array[,,"beta1"]

plot(beta1, type='l', col="red")

plot(density(beta1),lwd=2,col="red")

beta2 <- sims$sims.array[,,"beta2"]

plot(beta2, type='l', col="red")

plot(density(beta2),lwd=2,col="red")

beta3 <- sims$sims.array[,,"beta3"]

plot(beta3, type='l', col="red")

plot(density(beta3),lwd=2,col="red")

```

## displacement
```{r, echo=TRUE}
N <- 392

model <- function() {
for(i in 1:N){
mpg[i] ~ dnorm(mu[i], tau)
mu[i] <- alpha + beta1*model.year[i] + beta2*acceleration[i] + beta3*displacement[i] 
}
# priors
alpha ~ dnorm(0, .001)
beta1 ~ dunif(-1000,1000)
beta2 ~ dunif(-1000, 1000)
beta3 ~ dunif(-1000, 1000)
tau ~ dgamma(0.5,0.5)
}

logmpg <- log(cars$mpg)

data <- list(mpg=logmpg, model.year=cars$model.year, displacement = cars$displacement, acceleration=cars$acceleration, N=N)

inits <- function(){
list(alpha=rnorm(1), beta1 = rnorm(1), beta2 = rnorm(1), beta3 = rnorm(1), tau=runif(1,0,2))
}

parameters <- c("alpha", "beta1", "beta2", "beta3","tau")


sims <- bugs(data=data, inits=inits, parameters.to.save = c("alpha", "beta1", "beta2", "beta3", "tau"), model.file = model, n.chains=1, n.iter=100000, n.burnin=10000)
alpha<- sims$sims.array[,,"alpha"]

print(sims, digits.summary = 5)

plot(alpha, type='l', col="red")

plot(density(alpha), lwd=2, col="red")

tau <- sims$sims.array[,,"tau"]

plot(tau, type='l', col="red")

plot(density(tau), lwd=2, col="red")

beta1 <- sims$sims.array[,,"beta1"]

plot(beta1, type='l', col="red")

plot(density(beta1),lwd=2,col="red")

beta2 <- sims$sims.array[,,"beta2"]

plot(beta2, type='l', col="red")

plot(density(beta2),lwd=2,col="red")

beta3 <- sims$sims.array[,,"beta3"]

plot(beta3, type='l', col="red")

plot(density(beta3),lwd=2,col="red")

```

### horsepower

```{r, echo=TRUE}
N <- 392

model <- function() {
for(i in 1:N){
mpg[i] ~ dnorm(mu[i], tau)
mu[i] <- alpha + beta1*model.year[i] + beta2*acceleration[i] + beta3*horsepower[i] 
}
# priors
alpha ~ dnorm(0, .001)
beta1 ~ dnorm(1,0.01)
beta2 ~ dnorm(1, 0.01)
beta3 ~ dnorm(1, 0.01)
tau ~ dgamma(0.5,0.5)
}

logmpg <- log(cars$mpg)

data <- list(mpg=logmpg, model.year=cars$model.year, horsepower = cars$horsepower, acceleration=cars$acceleration, N=N)

inits <- function(){
list(alpha=rnorm(1), beta4 = rnorm(1), beta5 = rnorm(1), beta6 = rnorm(1), tau=runif(1,0,2))
}

parameters <- c("alpha", "beta1", "beta2", "beta3","tau")


sims <- bugs(data=data, inits=inits, parameters.to.save = c("alpha", "beta1", "beta2", "beta3", "tau"), model.file = model, n.chains=1, n.iter=100000, n.burnin=10000)

print(sims, digits.summary = 5)

plot(alpha, type='l', col="red")

plot(density(alpha), lwd=2, col="red")

tau <- sims$sims.array[,,"tau"]

plot(tau, type='l', col="red")

plot(density(tau), lwd=2, col="red")

beta1 <- sims$sims.array[,,"beta1"]

plot(beta1, type='l', col="red")

plot(density(beta1),lwd=2,col="red")

beta2 <- sims$sims.array[,,"beta2"]

plot(beta2, type='l', col="red")

plot(density(beta2),lwd=2,col="red")

beta3 <- sims$sims.array[,,"beta3"]

plot(beta3, type='l', col="red")

plot(density(beta3),lwd=2,col="red")
```

### Check results using brms
```{r, echo=TRUE}
best <- brm(data=cars, log(mpg) ~ model.year + weight + acceleration, prior = c(prior(uniform(-1000,1000), "b"), prior(normal(0, 1000), "Intercept"), prior(gamma(0.5, 0.5), "sigma")))
summary(best)
plot(best)
prior_summary(best)
```